# Generated by Django 5.1.3 on 2024-12-03 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("genero", models.CharField(max_length=100)),
                ("plataforma", models.CharField(max_length=100)),
                ("ano_lancamento", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quero_jogar", "Quero Jogar"),
                            ("abandonado", "Abandonado"),
                            ("jogando", "Jogando"),
                            ("zerado", "Zerado"),
                        ],
                        default="quero_jogar",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.IntegerField()),
                ("comentario", models.TextField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_catalog.jogo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                (
                    "jogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_catalog.jogo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TempoDeJogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tempo", models.FloatField()),
                (
                    "jogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_catalog.jogo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
